name: ms500db
channels:
  - defaults
dependencies:
  - python=3.8.0
  - pip=22.2.2
  - pip:
    - beautifulsoup4==4.11.1
    - bs4==0.0.1
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - future==0.18.2
    - idna==3.4
    - numpy==1.23.3
    - pandas==1.5.0
    - pillow==9.2.0
    - progressbar==2.5
    - pycparser==2.21
    - pyloudnorm==0.1.0
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - requests==2.28.1
    - scipy==1.9.1
    - six==1.16.0
    - soundfile==0.11.0
    - soupsieve==2.3.2.post1
    - sox==1.4.1
    - torch==1.12.1
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12

